### ISSUE TITLE
相关项目说明

### ISSUE THREAD

**Issue by paper520** [yelloxing/npm-downloads#59]
基本说明：本项目只是提供了浏览器端绘图的基本接口，额外接口由特定项目提供，这也是为了增加灵活性。

**Comment by yelloxing** [comment]
[clay-2d](https://github.com/yelloxing/clay-2d)：更友好的二维图形绘制接口

**Comment by yelloxing** [comment]
非接口项目，不过对使用caly.js有帮助的用例项目或相关项目，也推荐在这里登记一下@All
